In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('GPT-wiki-intro.csv')

In [3]:
df

,id,url,title,wiki_intro,generated_intro,title_len,wiki_intro_len,generated_intro_len,prompt,generated_text,prompt_tokens,generated_text_tokens
0,63064638,https://en.wikipedia.org/wiki/Sexhow%20railway...,Sexhow railway station,Sexhow railway station was a railway station b...,Sexhow railway station was a railway station l...,3,174,78,200 word wikipedia style introduction on 'Sexh...,"located in the town of Sexhow, on the Cumbria...",25,88
1,279621,https://en.wikipedia.org/wiki/Eti%C3%A4inen,Etiäinen,"In Finnish folklore, all places and things, an...","In Finnish folklore, all places and things, an...",1,187,80,200 word wikipedia style introduction on 'Etiä...,"animate or inanimate, have a spirit or ""etiäi...",26,101
2,287229,https://en.wikipedia.org/wiki/Inverse%20functi...,Inverse function theorem,"In mathematics, specifically differential calc...","In mathematics, specifically differential calc...",3,170,59,200 word wikipedia style introduction on 'Inve...,function theorem states that for every real-v...,26,65
3,26712375,https://en.wikipedia.org/wiki/Stepping%20on%20...,Stepping on Roses,is a Japanese shōjo manga series written and i...,is a Japanese shōjo manga series written and i...,3,335,121,200 word wikipedia style introduction on 'Step...,and illustrated by Maki Fujii. The series fol...,26,150
4,38894426,https://en.wikipedia.org/wiki/Rob%20Bradley,Rob Bradley,"Robert Milner ""Rob"" Bradley, Jr. (born August ...","Robert Milner ""Rob"" Bradley, Jr. (born August ...",2,170,136,200 word wikipedia style introduction on 'Rob ...,"29, 1973) is an American former professional ...",28,162
...,...,...,...,...,...,...,...,...,...,...,...,...
149995,44173767,https://en.wikipedia.org/wiki/Randy%20Borum,Randy Borum,Randy Borum is a Professor and Coordinator of ...,Randy Borum is a Professor and Coordinator of ...,2,185,71,200 word wikipedia style introduction on 'Rand...,of the Master of Fine Arts Program in Creativ...,25,92
149996,33564134,https://en.wikipedia.org/wiki/Sa%27och%20language,Sa'och language,"Sa'och (, also, ""Sauch"") is an endangered, nea...","Sa'och (, also, ""Sauch"") is an endangered, nuc...",2,175,134,200 word wikipedia style introduction on 'Sa'o...,"nuclear-speaking, isolate language of the Ath...",33,184
149997,4219548,https://en.wikipedia.org/wiki/Philip%20Hanawalt,Philip Hanawalt,Philip C. Hanawalt (born 1931) is an American ...,Philip C. Hanawalt (born 1931) is an American ...,2,166,191,200 word wikipedia style introduction on 'Phil...,American graphic artist and illustrator. He i...,30,272
149998,2625970,https://en.wikipedia.org/wiki/Vossius%20Gymnasium,Vossius Gymnasium,Vossius Gymnasium is a public gymnasium in Ams...,Vossius Gymnasium is a public gymnasium in the...,2,168,108,200 word wikipedia style introduction on 'Voss...,"the town of Vossius, Netherlands. It is named...",32,147
149999,32345102,https://en.wikipedia.org/wiki/Simone%20Stratigo,Simone Stratigo,"Simone Stratigo (, Symeon Filippos Stratigos; ...","Simone Stratigo (, Symeon Filippos Stratigos; ...",2,153,132,200 word wikipedia style introduction on 'Simo...,born 1 July 1979) is a Greek professional foo...,33,173

In [4]:
df.drop(['url','title_len','wiki_intro_len','generated_intro_len','prompt','generated_text','prompt_tokens','generated_text_tokens'],axis=1,inplace=True)
df

,id,title,wiki_intro,generated_intro
0,63064638,Sexhow railway station,Sexhow railway station was a railway station b...,Sexhow railway station was a railway station l...
1,279621,Etiäinen,"In Finnish folklore, all places and things, an...","In Finnish folklore, all places and things, an..."
2,287229,Inverse function theorem,"In mathematics, specifically differential calc...","In mathematics, specifically differential calc..."
3,26712375,Stepping on Roses,is a Japanese shōjo manga series written and i...,is a Japanese shōjo manga series written and i...
4,38894426,Rob Bradley,"Robert Milner ""Rob"" Bradley, Jr. (born August ...","Robert Milner ""Rob"" Bradley, Jr. (born August ..."
...,...,...,...,...
149995,44173767,Randy Borum,Randy Borum is a Professor and Coordinator of ...,Randy Borum is a Professor and Coordinator of ...
149996,33564134,Sa'och language,"Sa'och (, also, ""Sauch"") is an endangered, nea...","Sa'och (, also, ""Sauch"") is an endangered, nuc..."
149997,4219548,Philip Hanawalt,Philip C. Hanawalt (born 1931) is an American ...,Philip C. Hanawalt (born 1931) is an American ...
149998,2625970,Vossius Gymnasium,Vossius Gymnasium is a public gymnasium in Ams...,Vossius Gymnasium is a public gymnasium in the...
149999,32345102,Simone Stratigo,"Simone Stratigo (, Symeon Filippos Stratigos; ...","Simone Stratigo (, Symeon Filippos Stratigos; ..."

In [5]:

dfh=df.copy()
dfh.drop(['generated_intro'],axis=1,inplace=True)
dfh=dfh.head(50000)
dfh.rename(columns = {'wiki_intro':'text'}, inplace = True)
result=[]
for i in range(50000):
  result.append("Human Written")
dfh['result']=result
print(dfh)

             id                     title  \
0      63064638    Sexhow railway station
1        279621                  Etiäinen
2        287229  Inverse function theorem
3      26712375         Stepping on Roses
4      38894426               Rob Bradley
...         ...                       ...
49995   1119629            Word of wisdom
49996   4096346                 Ski Beatz
49997   1526322            Crispian Mills
49998   4592607               Russell Ash
49999  42161771  Afterglow Maverick Sabre

                                                    text         result
0      Sexhow railway station was a railway station b...  Human Written
1      In Finnish folklore, all places and things, an...  Human Written
2      In mathematics, specifically differential calc...  Human Written
3      is a Japanese shōjo manga series written and i...  Human Written
4      Robert Milner "Rob" Bradley, Jr. (born August ...  Human Written
...                                                  ...            ...
49995  In Christianity, the word of wisdom is a spiri...  Human Written
49996  David Anthony Willis, known professionally as ...  Human Written
49997  Crispian Mills (born 18 January 1973 as Crispi...  Human Written
49998  Russell Ash (18 June 1946 – 21 June 2010) was ...  Human Written
49999  Ch./Am. Ch. Afterglow Maverick Sabre (born 4 S...  Human Written

[50000 rows x 4 columns]

In [6]:

dfg=df.copy()
dfg.drop(['wiki_intro'],axis=1,inplace=True)
dfg=dfg.head(50000)
dfg.rename(columns = {'generated_intro':'text'}, inplace = True)
result=[]
for i in range(50000):
  result.append("AI Written")
dfg['result']=result
print(dfg)

             id                     title  \
0      63064638    Sexhow railway station
1        279621                  Etiäinen
2        287229  Inverse function theorem
3      26712375         Stepping on Roses
4      38894426               Rob Bradley
...         ...                       ...
49995   1119629            Word of wisdom
49996   4096346                 Ski Beatz
49997   1526322            Crispian Mills
49998   4592607               Russell Ash
49999  42161771  Afterglow Maverick Sabre

                                                    text      result
0      Sexhow railway station was a railway station l...  AI Written
1      In Finnish folklore, all places and things, an...  AI Written
2      In mathematics, specifically differential calc...  AI Written
3      is a Japanese shōjo manga series written and i...  AI Written
4      Robert Milner "Rob" Bradley, Jr. (born August ...  AI Written
...                                                  ...         ...
49995  In Christianity, the word of wisdom is a colle...  AI Written
49996  David Anthony Willis, known professionally as ...  AI Written
49997  Crispian Mills (born 18 January 1973 as Crispi...  AI Written
49998  Russell Ash (18 June 1946 – 21 December 2009) ...  AI Written
49999  Ch./Am. Ch. Afterglow Maverick Sabre (born 4/1...  AI Written

[50000 rows x 4 columns]

In [7]:
ds=pd.concat([dfh,dfg])
ds.shape

(100000, 4)

In [8]:
ds

,id,title,text,result
0,63064638,Sexhow railway station,Sexhow railway station was a railway station b...,Human Written
1,279621,Etiäinen,"In Finnish folklore, all places and things, an...",Human Written
2,287229,Inverse function theorem,"In mathematics, specifically differential calc...",Human Written
3,26712375,Stepping on Roses,is a Japanese shōjo manga series written and i...,Human Written
4,38894426,Rob Bradley,"Robert Milner ""Rob"" Bradley, Jr. (born August ...",Human Written
...,...,...,...,...
49995,1119629,Word of wisdom,"In Christianity, the word of wisdom is a colle...",AI Written
49996,4096346,Ski Beatz,"David Anthony Willis, known professionally as ...",AI Written
49997,1526322,Crispian Mills,Crispian Mills (born 18 January 1973 as Crispi...,AI Written
49998,4592607,Russell Ash,Russell Ash (18 June 1946 – 21 December 2009) ...,AI Written
49999,42161771,Afterglow Maverick Sabre,Ch./Am. Ch. Afterglow Maverick Sabre (born 4/1...,AI Written

In [9]:
ds.drop(['id','title'],axis=1,inplace=True)

In [10]:
from sklearn.preprocessing import LabelEncoder
le1=LabelEncoder()
ds['result']=le1.fit_transform(ds['result'])

In [11]:
ds

                                                    text  result
0      Sexhow railway station was a railway station b...       1
1      In Finnish folklore, all places and things, an...       1
2      In mathematics, specifically differential calc...       1
3      is a Japanese shōjo manga series written and i...       1
4      Robert Milner "Rob" Bradley, Jr. (born August ...       1
...                                                  ...     ...
49995  In Christianity, the word of wisdom is a colle...       0
49996  David Anthony Willis, known professionally as ...       0
49997  Crispian Mills (born 18 January 1973 as Crispi...       0
49998  Russell Ash (18 June 1946 – 21 December 2009) ...       0
49999  Ch./Am. Ch. Afterglow Maverick Sabre (born 4/1...       0

[100000 rows x 2 columns]

In [12]:
ds.rename(columns={'result':'labels'},inplace=True)

In [13]:
ds

                                                    text  labels
0      Sexhow railway station was a railway station b...       1
1      In Finnish folklore, all places and things, an...       1
2      In mathematics, specifically differential calc...       1
3      is a Japanese shōjo manga series written and i...       1
4      Robert Milner "Rob" Bradley, Jr. (born August ...       1
...                                                  ...     ...
49995  In Christianity, the word of wisdom is a colle...       0
49996  David Anthony Willis, known professionally as ...       0
49997  Crispian Mills (born 18 January 1973 as Crispi...       0
49998  Russell Ash (18 June 1946 – 21 December 2009) ...       0
49999  Ch./Am. Ch. Afterglow Maverick Sabre (born 4/1...       0

[100000 rows x 2 columns]

In [14]:
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("cardiffnlp/twitter-roberta-base-emotion")

C:\Users\Atharv\anaconda_new\envs\env_1\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [15]:
import re
def preprocess(text):
    text = re.sub(r'[^\w\s\']',' ', text)
    text = re.sub(' +', ' ', text)
    return text.strip().lower()

In [16]:
ds['text'] = ds['text'].map(preprocess)

In [17]:
ds

                                                    text  labels
0      sexhow railway station was a railway station b...       1
1      in finnish folklore all places and things and ...       1
2      in mathematics specifically differential calcu...       1
3      is a japanese shōjo manga series written and i...       1
4      robert milner rob bradley jr born august 24 19...       1
...                                                  ...     ...
49995  in christianity the word of wisdom is a collec...       0
49996  david anthony willis known professionally as s...       0
49997  crispian mills born 18 january 1973 as crispin...       0
49998  russell ash 18 june 1946 21 december 2009 was ...       0
49999  ch am ch afterglow maverick sabre born 4 12 19...       0

[100000 rows x 2 columns]

In [19]:
from datasets import Dataset, DatasetDict
dataset = Dataset.from_pandas(ds)
dataset

Dataset({
    features: ['text', 'labels', '__index_level_0__'],
    num_rows: 100000
})

In [21]:
def tokenize_data(example):
    return tokenizer(example['text'], max_length=512)

dataset = dataset.map(tokenize_data, batched=True)

Map:   0%|                                                                           | 0/100000 [00:00<?, ? examples/s]Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.

In [22]:
from sklearn.model_selection import train_test_split

train_testvalid = dataset.train_test_split(test_size=0.2)

test_valid = train_testvalid['test'].train_test_split(test_size=0.5)

dataset = DatasetDict({
    'train': train_testvalid['train'],
    'test': test_valid['test'],
    'valid': test_valid['train']})

dataset

DatasetDict({
    train: Dataset({
        features: ['text', 'labels', '__index_level_0__', 'input_ids', 'attention_mask'],
        num_rows: 80000
    })
    test: Dataset({
        features: ['text', 'labels', '__index_level_0__', 'input_ids', 'attention_mask'],
        num_rows: 10000
    })
    valid: Dataset({
        features: ['text', 'labels', '__index_level_0__', 'input_ids', 'attention_mask'],
        num_rows: 10000
    })
})

In [23]:
from transformers import TrainingArguments

training_args = TrainingArguments("test_trainer", num_train_epochs=3)

In [25]:
num_labels=ds['labels'].nunique()

In [27]:
from transformers import RobertaForSequenceClassification
model = RobertaForSequenceClassification.from_pretrained("cardiffnlp/twitter-roberta-base-emotion")

Downloading pytorch_model.bin: 100%|████████████████████████████████████████████████| 499M/499M [00:40<00:00, 12.2MB/s]
C:\Users\Atharv\anaconda_new\envs\env_1\Lib\site-packages\huggingface_hub\file_download.py:133: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Atharv\.cache\huggingface\hub. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

In [28]:
from transformers import Trainer
from datasets import load_metric
import numpy as np

metric = load_metric("accuracy")

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    return metric.compute(predictions=predictions, references=labels)

trainer = Trainer(
    model=model, args=training_args, train_dataset=dataset['train'], eval_dataset=dataset['valid'],tokenizer=tokenizer,compute_metrics=compute_metrics
)

C:\Users\Atharv\AppData\Local\Temp\ipykernel_3164\2251018262.py:5: FutureWarning: load_metric is deprecated and will be removed in the next major version of datasets. Use 'evaluate.load' instead, from the new library 🤗 Evaluate: https://huggingface.co/docs/evaluate
  metric = load_metric("accuracy")

In [ ]:
trainer.train()

C:\Users\Atharv\anaconda_new\envs\env_1\Lib\site-packages\transformers\optimization.py:391: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
You're using a RobertaTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.